//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRentalRecord
    {
        public int Rental_Id { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime RentDate { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public decimal Cost { get; set; }
        public int CarType { get; set; }
    
        public virtual TypeofCar TypeofCar { get; set; }
    }
}
