//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class userRole
    {
        public int userRole_id { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> roleID { get; set; }
    
        public virtual loginInfo loginInfo { get; set; }
        public virtual Role Role { get; set; }
    }
}
